import { Archetype } from '../types/operators'

export const ARCHETYPE: Archetype[] = [
  'Alchemist',
  'Artisan',
  'Explorer',
  'Illuminator',
  'Magician',
  'Memetic',
  'Oracle',
  'Outlaw',
  'Philosopher',
  'Polymath',
]

export const COMP = [
  'Ascii',
  'Ascii_RGB',
  'RetroScreen',
  'RetroVHS',
  'SketchStar',
]

export const BACKGROUND = [
  '[CAMOED]',
  '[CYPHERED]',
  '[REDACTED]',
  'Cypress',
  'LimeWire',
  'Mariana',
  'Marooned',
  'Nightfall',
  'Phantom',
  'Rust',
  'Sanguine',
  'Sulphur',
  'Void',
]

export const SKIN = [
  '[CAMOED]',
  '[CYPHERED]',
  '[REDACTED]',
  'IC1',
  'IC2',
  'IC3',
  'IC4',
  'IC6',
]

export const HELMET = [
  '[CAMOED]',
  '[CYPHERED]',
  '[REDACTED]',
  'Aquaflux cybernetic goggles',
  'Aquamarine immersive visor',
  'Aureate cybernetic goggles',
  'Aureate cypher gaiter',
  'Aureate harlequin mask',
  'Aurora crested helm',
  'Brimstone mindguard',
  'Brimstone nebula visor',
  'Canopy cybernetic goggles',
  'Canopy versatility goggles',
  'Celestial crested helm',
  'Cobalt mindguard',
  'Cobalt technomancer helm',
  'Cyberglow spartan hawk',
  'Ethereal crested helm',
  'Ferrous spartan hawk',
  'Gaudy immersive visor',
  'Garnet harlequin mask',
  'Holochrome spartan hawk',
  'Indigo cypher gaiter',
  'Inferno cybernetic goggles',
  'Inferno cypher gaiter',
  'Inferno immersive visor',
  'Inferno mindguard',
  'Inferno versatility goggles',
  'Iodine technomancer helm',
  'Iolite harlequin mask',
  'Iridium mindguard',
  'Jade harlequin mask',
  'Marine versatility goggles',
  'Mercurial cypher gaiter',
  'Mercurial mindguard',
  'Neon cybernetic goggles',
  'Neon spartan hawk',
  'Neon technomancer helm',
  'Nightshade immersive visor',
  'Nightshade nebula visor',
  'Onyx harlequin mask',
  'Oxide nebula visor',
  'Oxide technomancer helm',
  'Regal crested helm',
  'Sulphur technomancer helm',
  'Sulphur versatility goggles',
  'Tempest nebula visor',
  'Twilight cypher gaiter',
  'Verdant crested helm',
  'Verdigris spartan hawk',
  'Vespa nebula visor',
  'Wisteria immersive visor',
  'Zenith versatility goggles',
]

export const JACKET = [
  '[CAMOED]',
  '[CYPHERED]',
  '[REDACTED]',
  'Amethyst bomber jacket',
  'Amethyst coveralls',
  'Amethyst cowl',
  'Amethyst frock coat',
  'Amethyst funnel neck',
  'Amethyst fusion mantle',
  'Amethyst hoody',
  'Amethyst sakáki',
  'Amethyst tactical jacket',
  'Azure obscurer',
  'Canopy obscurer',
  'Carmine bomber jacket',
  'Carmine coveralls',
  'Carmine cowl',
  'Carmine frock coat',
  'Carmine funnel neck',
  'Carmine fusion mantle',
  'Carmine hoody',
  'Carmine obscurer',
  'Carmine sakáki',
  'Carmine tactical jacket',
  'Cobalt frock coat',
  'Cyan bomber jacket',
  'Cyan coveralls',
  'Cyan cowl',
  'Cyan funnel neck',
  'Cyan fusion mantle',
  'Cyan hoody',
  'Cyan sakáki',
  'Cyan tactical jacket',
  'Digital gold bomber jacket',
  'Digital gold coveralls',
  'Digital gold cowl',
  'Digital gold funnel neck',
  'Digital gold fusion mantle',
  'Digital gold hoody',
  'Digital gold sakáki',
  'Digital gold tactical jacket',
  'Dusk obscurer',
  'Emerald bomber jacket',
  'Emerald coveralls',
  'Emerald cowl',
  'Emerald frock coat',
  'Emerald funnel neck',
  'Emerald fusion mantle',
  'Emerald hoody',
  'Emerald sakáki',
  'Emerald tactical jacket',
  'Sulphur frock coat',
  'Sunset obscurer',
]
